package io.akka.intentkit.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.io.IOException;
import java.util.List;
import org.junit.jupiter.api.Test;

/**
 * SPEC-001 rules 1, 2, 3, 3a, 5, 6 — which schedules are accepted, and with which refusal.
 *
 * <p>Every expectation is read from {@code source-cron-answers.json}, generated by
 * {@code intentkit-port/probes/export_cron_fixture.py} from a recording of intentkit's own
 * validator and its own trigger. Nothing here is hand-written, so the test cannot drift
 * towards what this port happens to do.
 */
public class CronPolicyTest {

  private final SourceAnswers answers = SourceAnswers.load();

  @Test
  public void acceptsExactlyWhatTheSourceAcceptsAndCanRun() throws IOException {
    var wrong = answers.expressions().stream()
        .filter(e -> accepted(e.cron()) != e.portAccepts())
        .map(e -> e.cron() + " expected=" + e.portAccepts() + " actual=" + accepted(e.cron()))
        .toList();
    assertThat(wrong).isEmpty();
    // A fixture that accepted nothing would also pass the check above.
    assertThat(answers.expressions().stream().filter(SourceAnswers.Expression::portAccepts))
        .hasSizeGreaterThan(30);
  }

  @Test
  public void refusesWithTheSourcesOwnKey() {
    var wrong = answers.expressions().stream()
        .filter(e -> !e.portAccepts())
        .filter(e -> e.sourceKey() != null)
        .filter(e -> !e.sourceKey().equals(keyOf(e.cron())))
        .map(e -> e.cron() + " expected=" + e.sourceKey() + " actual=" + keyOf(e.cron()))
        .toList();
    assertThat(wrong).isEmpty();
  }

  /**
   * The four expressions intentkit stores and its own scheduler then cannot build. SPEC-001
   * decision 9: refused here, at write time, rather than accepted and never run.
   */
  @Test
  public void refusesWhatTheSourceAcceptsButCannotSchedule() {
    var diverging = answers.expressions().stream()
        .filter(e -> e.sourceAccepted() && !e.sourceBuildable())
        .map(SourceAnswers.Expression::cron)
        .toList();
    assertThat(diverging)
        .containsExactlyInAnyOrder(
            "0 0 */31 * *", "0 0 * */12 *", "5-3 0 * * *", "0 0 * * sun-sat");
    for (var cron : diverging) {
      assertThat(keyOf(cron)).isEqualTo("InvalidCronExpression");
    }
  }

  @Test
  public void anEmptyScheduleIsItsOwnRefusal() {
    for (var blank : List.of("", "   ")) {
      assertThatThrownBy(() -> CronPolicy.validate(blank))
          .isInstanceOf(ScheduleRejected.class)
          .hasFieldOrPropertyWithValue("key", "InvalidAutonomousConfig")
          .hasMessageContaining("cron must have a value");
    }
    assertThat(keyOf(null)).isEqualTo("InvalidAutonomousConfig");
  }

  /**
   * The interval refusal that does not bind. SPEC-001 decision 1: the accepted set is
   * copied, and the true gap is reported alongside it rather than the claim in the message.
   */
  @Test
  public void reportsTheGapTheRefusalMessageOnlyClaims() {
    var base = answers.base();
    for (var e : answers.expressions()) {
      if (!e.portAccepts() || e.minGapMinutes() == null) {
        continue;
      }
      var schedule = CronPolicy.validate(e.cron());
      assertThat(schedule.minGapMinutes(base))
          .as("min gap for %s", e.cron())
          .isEqualTo(e.minGapMinutes().longValue());
    }
    assertThat(CronPolicy.validate("*/2 0 * * *").minGapMinutes(base)).isEqualTo(2);
    assertThat(CronPolicy.validate("0-5 2 * * *").minGapMinutes(base)).isEqualTo(1);
    assertThat(CronPolicy.validate("*/59 * * * *").minGapMinutes(base)).isEqualTo(1);
  }

  private boolean accepted(String cron) {
    try {
      CronPolicy.validate(cron);
      return true;
    } catch (ScheduleRejected e) {
      return false;
    }
  }

  private String keyOf(String cron) {
    try {
      CronPolicy.validate(cron);
      return null;
    } catch (ScheduleRejected e) {
      return e.key();
    }
  }
}
