package io.akka.intentkit.domain;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.time.Instant;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * What intentkit answered, read back from the probe recording.
 *
 * <p>The file is generated by {@code intentkit-port/probes/export_cron_fixture.py} from
 * {@code probes/probe-01-results.json}. Tests assert against this rather than against
 * literals so that a claim in a test is always a claim about the source.
 */
public record SourceAnswers(Instant base, Instant calendarBase, List<Expression> expressions) {

  public record Expression(
      String cron,
      boolean sourceAccepted,
      boolean sourceBuildable,
      boolean portAccepts,
      String sourceKey,
      Double minGapMinutes,
      List<Instant> fires,
      List<String> weekdays,
      Instant firstFire) {}

  public static SourceAnswers load() {
    try (var in = SourceAnswers.class.getResourceAsStream("/source-cron-answers.json")) {
      if (in == null) {
        throw new IllegalStateException(
            "source-cron-answers.json is missing — regenerate it with "
                + "python intentkit-port/probes/export_cron_fixture.py");
      }
      JsonNode root = new ObjectMapper().readTree(in);
      var expressions = new ArrayList<Expression>();
      for (JsonNode e : root.get("expressions")) {
        expressions.add(
            new Expression(
                e.get("cron").asText(),
                e.path("sourceAccepted").asBoolean(),
                e.path("sourceBuildable").asBoolean(),
                e.path("portAccepts").asBoolean(),
                e.hasNonNull("sourceKey") ? e.get("sourceKey").asText() : null,
                e.hasNonNull("minGapMinutes") ? e.get("minGapMinutes").asDouble() : null,
                instants(e.path("fires")),
                strings(e.path("weekdays")),
                e.hasNonNull("firstFire") ? instant(e.get("firstFire").asText()) : null));
      }
      return new SourceAnswers(
          instant(root.get("base").asText()),
          instant(root.get("calendar_base").asText()),
          List.copyOf(expressions));
    } catch (IOException e) {
      throw new UncheckedIOException(e);
    }
  }

  private static Instant instant(String iso) {
    return OffsetDateTime.parse(iso).toInstant();
  }

  private static List<Instant> instants(JsonNode array) {
    if (!array.isArray()) {
      return List.of();
    }
    var out = new ArrayList<Instant>();
    array.forEach(n -> out.add(instant(n.asText())));
    return List.copyOf(out);
  }

  private static List<String> strings(JsonNode array) {
    if (!array.isArray()) {
      return List.of();
    }
    var out = new ArrayList<String>();
    array.forEach(n -> out.add(n.asText()));
    return List.copyOf(out);
  }
}
